version: "3"

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
    volumes:
      - ./compose-data/mariadb:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 10001:8080